Vagrant.configure("2") do |config|

  config.vm.define "etcd1" do |v|
    v.vm.box = "shakirshakiel/centos_etcd"
    v.vm.box_version = "3.4.9"
    v.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    v.vm.network "private_network", ip: "192.168.199.31"
  end

end
  