backup:
  - key: "backup-daily"
    enabled: "true"
    cronExp: "0 0 2 ? * MON-FRI"
    retentionPeriodHours: "0"
    createArchive: "false"
    excludedRepositories: null
    sendMailOnError: "true"
    excludeNewRepositories: "false"
    precalculate: "false"
    
  - key: "backup-weekly"
    enabled: "false"
    cronExp: "0 0 2 ? * SAT"
    retentionPeriodHours: "336"
    createArchive: "false"
    excludedRepositories: null
    sendMailOnError: "true"
    excludeNewRepositories: "false"
    precalculate: "false"
  }
