Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory.ini"
    # ansible.raw_arguments = ["-vvvv"]
    # ansible.tags = "test"
  end

  config.vm.define "zookeeper1" do |v|
    v.vm.box = "shakirshakiel/centos_zookeeper"
    v.vm.box_version = "3.6.1"
    v.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    v.vm.network "private_network", ip: "192.168.199.21"
  end

  config.vm.define "zookeeper2" do |v|
    v.vm.box = "shakirshakiel/centos_zookeeper"
    v.vm.box_version = "3.6.1"
    v.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    v.vm.network "private_network", ip: "192.168.199.22"
  end

  config.vm.define "zookeeper3" do |v|
    v.vm.box = "shakirshakiel/centos_zookeeper"
    v.vm.box_version = "3.6.1"
    v.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    v.vm.network "private_network", ip: "192.168.199.23"
  end

end
  