- name: start artifactory service
  become: yes
  service:
    name: artifactory
    state: "{{ state }}"
    daemon_reload: yes
    enabled: yes

- name: Wait for artifactory to start
  become: yes
  when: not ansible_check_mode
  uri:
    url: http://127.0.0.1:8082/router/api/v1/system/health
    status_code: 200
  register: result
  until: "(result.status == 200) and (result.json | server_healthy)"
  retries: 10
  delay: 5
