- name: Install ldap authorisation plugin
  become: yes
  get_url:
    url: "https://github.com/gocd/gocd-ldap-authorization-plugin/releases/download/v4.2.0-73/gocd-ldap-authorization-plugin-4.2.0-73.jar"
    checksum: "sha256:dd636b963239ce50f5945303ce5c897b949a7921c33c92874b85f9ca52a064ee"
    dest: "/data/var-lib-go-server/plugins/external"
    mode: 0644
    owner: go
    group: go
  notify: "restart gocd server"
