---

- name: configure gocd server
  hosts: gocd_server
  roles:
    - gocd_server

- name: configure gocd linux agent
  hosts: gocd_agents
  roles:
    - gocd_agent

- name: configure gocd mac agent
  hosts: gocd_mac_agents
  roles:
    - gocd_mac_agent
