Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory.ini"
    # ansible.raw_arguments = ["-v"]
    # ansible.tags = "test"
  end

  config.vm.define "server" do |server|
    server.vm.box = "shakirshakiel/centos_docker"
    server.vm.box_version = "19.03.1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    server.vm.network "private_network", ip: "192.168.199.11"
    server.vm.synced_folder 'vagrant-cache', '/vagrant-cache', owner: 'root', group: 'root'
  end

  1.upto(2) do |agent_number|
    config.vm.define "agent#{agent_number}" do |agent|
      agent.vm.box = "shakirshakiel/centos_docker"
      agent.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
      end
      agent.vm.box_version = "19.03.1"
      agent.vm.network "private_network", ip: "192.168.199.#{11 + agent_number}"
      agent.vm.synced_folder 'vagrant-cache', '/vagrant-cache', owner: 'root', group: 'root'
    end
  end

end
  