Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory.ini"
#     ansible.raw_arguments = ["-vvvv"]
#     ansible.tags = "test"
  end

  config.vm.define "artifactory" do |v|
    v.vm.box = "shakirshakiel/centos_docker"
    v.vm.box_version = "19.03.1"
    v.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end  
    v.vm.network "private_network", ip: "192.168.199.51"
    v.vm.synced_folder 'vagrant-cache', '/vagrant-cache', owner: 'root', group: 'root'
  end

end
  